name: Release

on:
  push:
    branches: [ master ]

jobs:
  build:
    name: Test & Build

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Install dependencies
      run: lein deps
    - name: Run tests
      run: lein eftest
    - name: Build artefact
      run: lein uberjar

  release:
    name: Release
    needs: build

    runs-on: ubuntu-latest

    steps:
    - name: Publish image
      uses: elgohr/Publish-Docker-Github-Action@master
      with:
        name: rafasf/walk-the-wall
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
        tag_semver: true
